### ISSUE TITLE
大牛牛，能不能弄个支持多源的例子

### ISSUE THREAD

**Issue by skyformat99** [Chris2018998/BeeCP-Starter#1]
比如说，一个里面支持多个数据源的例子
从MySQL读，写入postgreSQL
或者Redis读，写入MySQL等等
最好能把常见的数据库都搞进来
特别是最近流行的newSQL
比如tidb，cockroachDB等等

**Comment by Chris2018998** [comment]
您给的这个称谓, 个人太惭愧了.

目前最新版本(1.3.1)已经支持多数据源了

我尽快检验, 看是否能支持这些数据库.

**Comment by Chris2018998** [comment]
提供两个可运行的完整源码参考

单数据源案例: https://github.com/Chris2018998/BeeCP-Starter/blob/master/doc/SingleDataSourceTest.zip
多数据源案例: https://github.com/Chris2018998/BeeCP-Starter/blob/master/doc/MutilDataSourceTest.zip

**Comment by skyformat99** [comment]
完美解决方案啊
