### ISSUE TITLE
监控针对的是本身的多数据源嘛

### ISSUE THREAD

**Issue by xinwu-yang** [Chris2018998/BeeCP-Starter#15]
我目前使用的是Baomidou的多数据源管理，在监控页面无法获取当前配置的数据源以及SQL等信息

**Comment by xinwu-yang** [comment]
是需要我将我的数据源注册到Spring容器吗？

**Comment by Chris2018998** [comment]
从源码上看，Baomidou没有提供监控界面？建议咨询一下项目的Owner，如果没有的话，可以提一个需求。

BeeCP-Starter是有监控界面的，简单配置一下配置即可， 不需要再将数据源注册到容器。

**Comment by xinwu-yang** [comment]
@Chris2018998 意思是我如果使用Baomidou多数据源管理的话，则无法使用BeeCP-Starter提供的监控页面吗？

**Comment by Chris2018998** [comment]
是的。可以提一个需求，让Baomidou把监控界面移植过去或重新做一个新的。

**Comment by xinwu-yang** [comment]
好的
