### ISSUE TITLE
建议 artifactId 改为 beecp-spring-boot-starter

### ISSUE THREAD

**Issue by ChinaLym** [Chris2018998/BeeCP-Starter#3]
# 建议
 artifactId 改为 `beecp-spring-boot-starter`

`spring boot` 提供的 `starter` 都是以 `spring-boot-starter-xxx` 的方式命名的，Spring Boot 官方建议自定义的 `starter` 以`xxx-spring-boot-starter` 命名予以区分。见 [Spring Boot官方说明](https://docs.spring.io/spring-boot/docs/2.3.0.RELEASE/reference/htmlsingle/#using-boot-starter)

# 支持作者
感觉 `BeeCP` 不错，打算引入至自己写的 `Spring Boot` 扩展框架 [Shoulder-Framework（https://github.com/ChinaLym/Shoulder-Framework）](https://github.com/ChinaLym/Shoulder-Framework) 中作为默认的数据库连接池。

**Comment by Chris2018998** [comment]
好的,感谢支持,下一版本进行调整
